apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nfspvc-operator.fullname" . }}-manager-role
  labels:
    {{- include "nfspvc-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - persistentvolumeclaims
  verbs:
    - create
    - delete
    - get
    - list
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - persistentvolumes
  verbs:
    - create
    - delete
    - get
    - list
    - update
    - watch
- apiGroups:
    - nfspvc.dana.io
  resources:
    - nfspvcs
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - nfspvc.dana.io
  resources:
    - nfspvcs/finalizers
  verbs:
    - update
- apiGroups:
    - nfspvc.dana.io
  resources:
    - nfspvcs/status
  verbs:
    - get
    - patch
    - update