apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-aggregate-to-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    {{- include "nfspvc-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - nfspvc.dana.io
  resources:
  - nfspvcs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch