apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "nfspvc-operator.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "nfspvc-operator.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "nfspvc-operator.fullname" . }}-serving-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "nfspvc-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-nfspvc-dana-io-v1alpha1-nfspvc
  failurePolicy: Fail
  name: vnfspvc.kb.io
  rules:
  - apiGroups:
    - nfspvc.dana.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nfspvcs
  sideEffects: None