apiVersion: v1
kind: Service
metadata:
  name: {{ include "nfspvc-operator.fullname" . }}-webhook-service
  labels:
    {{- include "nfspvc-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.webhookService.ports.port }}
      protocol: {{ .Values.webhookService.ports.protocol }}
      targetPort: {{ .Values.webhookService.ports.targetPort }}
  selector:
    control-plane: controller-manager